package com.zoo.santuario.service;

import com.zoo.santuario.dto.CuidadorRequestDTO;
import com.zoo.santuario.dto.CuidadorResponseDTO;
import com.zoo.santuario.model.Cuidador;
import com.zoo.santuario.repository.CuidadorRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;

@Service
public class CuidadorService {

    @Autowired
    private CuidadorRepository cuidadorRepository;

    public List<CuidadorResponseDTO> getAllCuidadores() {
        return cuidadorRepository.findAll().stream()
                .map(this::convertToDto)
                .collect(Collectors.toList());
    }

    public Optional<CuidadorResponseDTO> getCuidadorById(Long id) {
        return cuidadorRepository.findById(id)
                .map(this::convertToDto);
    }

    public CuidadorResponseDTO createCuidador(CuidadorRequestDTO cuidadorRequestDTO) {
        if (cuidadorRepository.findByContact(cuidadorRequestDTO.getContact()).isPresent()) {
            throw new IllegalArgumentException("A cuidador with this contact already exists.");
        }
        Cuidador cuidador = convertToEntity(cuidadorRequestDTO);
        Cuidador savedCuidador = cuidadorRepository.save(cuidador);
        return convertToDto(savedCuidador);
    }

    public Optional<CuidadorResponseDTO> updateCuidador(Long id, CuidadorRequestDTO cuidadorRequestDTO) {
        return cuidadorRepository.findById(id)
                .map(existingCuidador -> {
                    // Check if the contact is being changed to an existing one by another cuidador
                    if (!existingCuidador.getContact().equals(cuidadorRequestDTO.getContact())) {
                        if (cuidadorRepository.findByContact(cuidadorRequestDTO.getContact()).isPresent()) {
                            throw new IllegalArgumentException("A cuidador with this contact already exists.");
                        }
                    }
                    existingCuidador.setName(cuidadorRequestDTO.getName());
                    existingCuidador.setContact(cuidadorRequestDTO.getContact());
                    existingCuidador.setSpecialty(cuidadorRequestDTO.getSpecialty());
                    existingCuidador.setStatus(cuidadorRequestDTO.getStatus());
                    Cuidador updatedCuidador = cuidadorRepository.save(existingCuidador);
                    return convertToDto(updatedCuidador);
                });
    }

    public boolean deleteCuidador(Long id) {
        if (cuidadorRepository.existsById(id)) {
            cuidadorRepository.deleteById(id);
            return true;
        }
        return false;
    }

    private CuidadorResponseDTO convertToDto(Cuidador cuidador) {
        return new CuidadorResponseDTO(
                cuidador.getId(),
                cuidador.getName(),
                cuidador.getContact(),
                cuidador.getSpecialty(),
                cuidador.getStatus()
        );
    }

    private Cuidador convertToEntity(CuidadorRequestDTO cuidadorRequestDTO) {
        return new Cuidador(
                null, // ID will be generated by the database
                cuidadorRequestDTO.getName(),
                cuidadorRequestDTO.getContact(),
                cuidadorRequestDTO.getSpecialty(),
                cuidadorRequestDTO.getStatus()
        );
    }
}